### ISSUE TITLE
Panic in polkadot relay

### ISSUE THREAD

**Issue by vgeddes** [Snowfork/snowbridge#513]
In staging environment.

Logs:
```
time="2021-09-02T09:36:47Z" level=info msg="4: Updating item 11 status from 'InitialVerificationTxConfirmed' to 'ReadyToComplete'"
time="2021-09-02T09:36:48Z" level=info msg="Complete Signature Commitment transaction submitted" txHash=0xd9082ee29a356b971df4d40549c3df1832b174419543ce056fe4457ee7897103
time="2021-09-02T09:36:48Z" level=info msg="5: Updating item status from 'ReadyToComplete' to 'CompleteVerificationTxSent'"
time="2021-09-02T09:36:48Z" level=info msg="Updating item in database..."
time="2021-09-02T09:36:48Z" level=error msg="Failed to get random validator bitfield" error="abi: attempting to unmarshall an empty string while arguments are expected"
time="2021-09-02T09:36:48Z" level=error msg="Failed to write complete signature commitment" error="abi: attempting to unmarshall an empty string while arguments are expected"
time="2021-09-02T09:36:48Z" level=info msg="Shutting down ethereum writer" reason="abi: attempting to unmarshall an empty string while arguments are expected"
time="2021-09-02T09:36:48Z" level=error msg="Failure fetching inclusion block" error="websocket: close 1011 (internal server error): Internal response error"
time="2021-09-02T09:36:48Z" level=info msg="4: Updating item 12 status from 'InitialVerificationTxConfirmed' to 'ReadyToComplete'"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ecfaa]

goroutine 99 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Hash(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vincent/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.6/core/types/block.go:377 +0x4a
github.com/snowfork/snowbridge/relayer/relays/beefy.(*BeefyEthereumListener).forwardReadyToCompleteItems(0xc000422780, 0xfbf178, 0xc000422800, 0xa726b2, 0x3, 0x0, 0x0)
        /home/vincent/code/snowbridge/relayer/relays/beefy/beefy-ethereum-listener.go:503 +0x2b0
github.com/snowfork/snowbridge/relayer/relays/beefy.(*BeefyEthereumListener).pollEventsAndHeaders(0xc000422780, 0xfbf178, 0xc000422800, 0x3, 0x0, 0x0)
        /home/vincent/code/snowbridge/relayer/relays/beefy/beefy-ethereum-listener.go:175 +0x45d
github.com/snowfork/snowbridge/relayer/relays/beefy.(*BeefyEthereumListener).Start.func1(0x0, 0x0)
        /home/vincent/code/snowbridge/relayer/relays/beefy/beefy-ethereum-listener.go:92 +0x7e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000b7860, 0xc0000bfa40)
        /home/vincent/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/vincent/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

**Comment by musnit** [comment]
@vgeddes you mean beefy relay? and did it restart and resume nicely or panic and stall indefinitely?

**Comment by vgeddes** [comment]
Yeah the beefy relay. This is non-critical error. The relay just restarts and continues happily.

**Comment by vgeddes** [comment]
Moved to Linear: SNO-149
